import type { Metadata } from "next";
import "./globals.css";
import { FavouritesProvider } from "@/contexts/favourites/FavouritesContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FavouritesProvider>
        <body>{children}</body>
      </FavouritesProvider>
    </html>
  );
}
